###### Base
FROM node:16-stretch as base
# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer installs, work.
RUN apt-get update && apt-get install -y wget --no-install-recommends \
  && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y libxss1 libxtst6 google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
  --no-install-recommends \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get purge --auto-remove -y curl \
  && rm -rf /src/*.deb

###### Packages
FROM base as packages
WORKDIR /app
COPY package*.json ./
RUN npm install

###### Source
FROM packages as source
WORKDIR /app
COPY . .

###### Test
FROM source as test
RUN npm run test

###### Run
FROM nginx:alpine
COPY --from=test /app/coverage /test-results

# docker build  -f dockerfile.test -t ultraviolet-radiation-test .
# docker run -it --rm -p 4200:80 ultraviolet-radiation-test